FROM alpine:3.8

ENV GOPATH /go
RUN apk update \
	&& apk add \
		 go \
		 git \
		 musl-dev \
		 mercurial
COPY . /go/src/github.com/seiji-thirdbridge/resolvable
WORKDIR /go/src/github.com/seiji-thirdbridge/resolvable
RUN go get
CMD go get \
	&& go build -ldflags "-X main.Version dev" -o /bin/resolvable \
	&& exec /bin/resolvable
